version: "3.3"
services:

  postgres-db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  app:
    build:
      ./wasd-gateway
    env_file:
      - ./wasd-gateway/variables.env
    ports:
      - "9080:9080"
    networks:
      - backend
    command: ["/application/start.sh"]
